### ISSUE TITLE
Add .gitignore

### ISSUE THREAD

**Issue by ariedamuco** [regulyagoston/Assignment-Team-1#1]
Please add gitignore.

**Comment by regulyagoston** [comment]
How can we add it to github? I have added it on my laptop but it is unclear how to extend this onto github... Can you give a glimps how to do it?

**Comment by ariedamuco** [comment]
Add a new line `data` to .gitignore. If you have already done this commit and push .gitingore. (.gitignore is just like any other .txt file.)
